### ISSUE TITLE
[BUG] not working tox env: docs

### ISSUE THREAD

**Issue by netzulo** [netzulo/qacode#211]
### Obtained Behaviour

**Not working sometimes** on windows and always failed on linux tox environment named **docs**

### Expected Behaviour

**Working always** on windows/linux tox environment named **docs**

#### Notes

fixed code env

``` ini
[testenv:docs]
commands = 
    python setup.py sdist
    check-manifest --ignore tox.ini,tests*,docs*,source-docs*
    twine check dist/*
    sphinx-build -M html source-docs/source ../docs
deps =
    check-manifest
    twine
    readme_renderer
    Sphinx
```

**Comment by netzulo** [comment]
WIP 

```
(qacode) [ntz@ntz-qa]/opt/ntz/qacode: sphinx-build -M html source-docs/source docs
Running Sphinx v1.3.6
loading pickled environment... done
building [mo]: targets for 0 po files that are out of date
building [html]: targets for 0 source files that are out of date
updating environment: 0 added, 6 changed, 0 removed
reading sources... [100%] _static/testlink
/opt/ntz/qacode/source-docs/source/_static/bots.rst:6: WARNING: autodoc: failed to import module u'qacode.core.bots.bot_base'; the following exception was raised:
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/sphinx/ext/autodoc.py", line 386, in import_object
    __import__(self.modname)
  File "/opt/ntz/qacode/qacode/__init__.py", line 9, in <module>
    from qacode import core
  File "/opt/ntz/qacode/qacode/core/__init__.py", line 5, in <module>
    from qacode.core import bots
  File "/opt/ntz/qacode/qacode/core/bots/__init__.py", line 5, in <module>
    from qacode.core.bots import bot_base
  File "/opt/ntz/qacode/qacode/core/bots/bot_base.py", line 7, in <module>
    from qacode.core.bots.modules.nav_base import NavBase
  File "/opt/ntz/qacode/qacode/core/bots/modules/__init__.py", line 5, in <module>
    from qacode.core.bots.modules import nav_base
  File "/opt/ntz/qacode/qacode/core/bots/modules/nav_base.py", line 10, in <module>
    from qacode.core.exceptions.core_exception import CoreException
  File "/opt/ntz/qacode/qacode/core/exceptions/__init__.py", line 5, in <module>
    from qacode.core.exceptions import control_exception
  File "/opt/ntz/qacode/qacode/core/exceptions/control_exception.py", line 5, in <module>
    from qacode.core.exceptions.core_exception import CoreException
  File "/opt/ntz/qacode/qacode/core/exceptions/core_exception.py", line 5, in <module>
    from qacode.core.loggers.logger_manager import LoggerManager
  File "/opt/ntz/qacode/qacode/core/loggers/__init__.py", line 5, in <module>
    from qacode.core.loggers import logger_manager
  File "/opt/ntz/qacode/qacode/core/loggers/logger_manager.py", line 6, in <module>
    from qautils.files import path_format
ImportError: No module named qautils.files
/opt/ntz/qacode/source-docs/source/_static/bots.rst:10: WARNING: autodoc: failed to import class u'BotBase' from module u'qacode.core.bots.bot_base'; the following exception was raised:
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/sphinx/ext/autodoc.py", line 386, in import_object
    __import__(self.modname)
  File "/opt/ntz/qacode/qacode/__init__.py", line 8, in <module>
    from qacode import configs
ImportError: cannot import name configs
/opt/ntz/qacode/source-docs/source/_static/bots.rst:16: WARNING: autodoc: failed to import module u'qacode.core.bots.modules.nav_base'; the following exception was raised:
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/sphinx/ext/autodoc.py", line 386, in import_object
    __import__(self.modname)
  File "/opt/ntz/qacode/qacode/__init__.py", line 8, in <module>
    from qacode import configs
ImportError: cannot import name configs
/opt/ntz/qacode/source-docs/source/_static/bots.rst:20: WARNING: autodoc: failed to import class u'NavBase' from module u'qacode.core.bots.modules.nav_base'; the following exception was raised:
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/sphinx/ext/autodoc.py", line 386, in import_object
    __import__(self.modname)
  File "/opt/ntz/qacode/qacode/__init__.py", line 8, in <module>
    from qacode import configs
ImportError: cannot import name configs
/opt/ntz/qacode/source-docs/source/_static/controls.rst:6: WARNING: autodoc: failed to import module u'qacode.core.webs.controls.control_base'; the following exception was raised:
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/sphinx/ext/autodoc.py", line 386, in import_object
    __import__(self.modname)
  File "/opt/ntz/qacode/qacode/__init__.py", line 8, in <module>
    from qacode import configs
ImportError: cannot import name configs
/opt/ntz/qacode/source-docs/source/_static/controls.rst:10: WARNING: autodoc: failed to import class u'ControlBase' from module u'qacode.core.webs.controls.control_base'; the following exception was raised:
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/sphinx/ext/autodoc.py", line 386, in import_object
    __import__(self.modname)
  File "/opt/ntz/qacode/qacode/__init__.py", line 8, in <module>
    from qacode import configs
ImportError: cannot import name configs
/opt/ntz/qacode/source-docs/source/_static/controls.rst:15: WARNING: autodoc: failed to import module u'qacode.core.webs.controls.control_form'; the following exception was raised:
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/sphinx/ext/autodoc.py", line 386, in import_object
    __import__(self.modname)
  File "/opt/ntz/qacode/qacode/__init__.py", line 8, in <module>
    from qacode import configs
ImportError: cannot import name configs
/opt/ntz/qacode/source-docs/source/_static/controls.rst:19: WARNING: autodoc: failed to import class u'ControlForm' from module u'qacode.core.webs.controls.control_form'; the following exception was raised:
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/sphinx/ext/autodoc.py", line 386, in import_object
    __import__(self.modname)
  File "/opt/ntz/qacode/qacode/__init__.py", line 8, in <module>
    from qacode import configs
ImportError: cannot import name configs
/opt/ntz/qacode/source-docs/source/_static/controls.rst:24: WARNING: autodoc: failed to import module u'qacode.core.webs.controls.control_group'; the following exception was raised:
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/sphinx/ext/autodoc.py", line 386, in import_object
    __import__(self.modname)
  File "/opt/ntz/qacode/qacode/__init__.py", line 8, in <module>
    from qacode import configs
ImportError: cannot import name configs
/opt/ntz/qacode/source-docs/source/_static/controls.rst:28: WARNING: autodoc: failed to import class u'ControlGroup' from module u'qacode.core.webs.controls.control_group'; the following exception was raised:
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/sphinx/ext/autodoc.py", line 386, in import_object
    __import__(self.modname)
  File "/opt/ntz/qacode/qacode/__init__.py", line 8, in <module>
    from qacode import configs
ImportError: cannot import name configs
/opt/ntz/qacode/source-docs/source/_static/loggers.rst:6: WARNING: autodoc: failed to import module u'qacode.core.loggers.logger_manager'; the following exception was raised:
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/sphinx/ext/autodoc.py", line 386, in import_object
    __import__(self.modname)
  File "/opt/ntz/qacode/qacode/__init__.py", line 8, in <module>
    from qacode import configs
ImportError: cannot import name configs
/opt/ntz/qacode/source-docs/source/_static/loggers.rst:10: WARNING: autodoc: failed to import class u'LoggerManager' from module u'qacode.core.bots.loggers.logger_manager'; the following exception was raised:
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/sphinx/ext/autodoc.py", line 386, in import_object
    __import__(self.modname)
  File "/opt/ntz/qacode/qacode/__init__.py", line 8, in <module>
    from qacode import configs
ImportError: cannot import name configs
/opt/ntz/qacode/source-docs/source/_static/pages.rst:6: WARNING: autodoc: failed to import module u'qacode.core.webs.pages.page_base'; the following exception was raised:
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/sphinx/ext/autodoc.py", line 386, in import_object
    __import__(self.modname)
  File "/opt/ntz/qacode/qacode/__init__.py", line 8, in <module>
    from qacode import configs
ImportError: cannot import name configs
/opt/ntz/qacode/source-docs/source/_static/pages.rst:10: WARNING: autodoc: failed to import class u'PageBase' from module u'qacode.core.webs.pages.page_base'; the following exception was raised:
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/sphinx/ext/autodoc.py", line 386, in import_object
    __import__(self.modname)
  File "/opt/ntz/qacode/qacode/__init__.py", line 8, in <module>
    from qacode import configs
ImportError: cannot import name configs
/opt/ntz/qacode/source-docs/source/_static/testing.rst:6: WARNING: autodoc: failed to import module u'qacode.core.testing.test_info'; the following exception was raised:
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/sphinx/ext/autodoc.py", line 386, in import_object
    __import__(self.modname)
  File "/opt/ntz/qacode/qacode/__init__.py", line 8, in <module>
    from qacode import configs
ImportError: cannot import name configs
/opt/ntz/qacode/source-docs/source/_static/testing.rst:10: WARNING: autodoc: failed to import class u'TestInfoBase' from module u'qacode.core.testing.test_info'; the following exception was raised:
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/sphinx/ext/autodoc.py", line 386, in import_object
    __import__(self.modname)
  File "/opt/ntz/qacode/qacode/__init__.py", line 8, in <module>
    from qacode import configs
ImportError: cannot import name configs
/opt/ntz/qacode/source-docs/source/_static/testing.rst:15: WARNING: autodoc: failed to import module u'qacode.core.testing.test_info'; the following exception was raised:
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/sphinx/ext/autodoc.py", line 386, in import_object
    __import__(self.modname)
  File "/opt/ntz/qacode/qacode/__init__.py", line 8, in <module>
    from qacode import configs
ImportError: cannot import name configs
/opt/ntz/qacode/source-docs/source/_static/testing.rst:19: WARNING: autodoc: failed to import class u'TestInfoBot' from module u'qacode.core.testing.test_info'; the following exception was raised:
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/sphinx/ext/autodoc.py", line 386, in import_object
    __import__(self.modname)
  File "/opt/ntz/qacode/qacode/__init__.py", line 8, in <module>
    from qacode import configs
ImportError: cannot import name configs
/opt/ntz/qacode/source-docs/source/_static/testlink.rst:6: WARNING: autodoc: failed to import module u'qacode.core.testing.testlink.testlink_base'; the following exception was raised:
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/sphinx/ext/autodoc.py", line 386, in import_object
    __import__(self.modname)
  File "/opt/ntz/qacode/qacode/__init__.py", line 8, in <module>
    from qacode import configs
ImportError: cannot import name configs
/opt/ntz/qacode/source-docs/source/_static/testlink.rst:10: WARNING: autodoc: failed to import class u'TlBase' from module u'qacode.core.testing.testlink.testlink_base'; the following exception was raised:
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/sphinx/ext/autodoc.py", line 386, in import_object
    __import__(self.modname)
  File "/opt/ntz/qacode/qacode/__init__.py", line 8, in <module>
    from qacode import configs
ImportError: cannot import name configs
looking for now-outdated files... none found
pickling environment... done
checking consistency... done
preparing documents... done
writing output... [100%] index
generating indices... genindex
writing additional pages... search
copying static files... done
copying extra files... done
dumping search index in English (code: en) ... done
dumping object inventory... done
build succeeded, 20 warnings.

Build finished. The HTML pages are in docs/html.
```
